#ifndef SEMANTIC_SYMBOLS
#define SEMANTIC_SYMBOLS

#define SYMBOL_IDENTIFIER     1
#define SYMBOL_CHAR     2
#define SYMBOL_INTEGER     2
#define SYMBOL_REAL    3
#define SYMBOL_STRING     4
#define SYMBOL_CHAR_PTR  5
#define SYMBOL_FLOAT_PTR  5
#define SYMBOL_INT_PTR  6
#define SYMBOL_FUNC_INT 7
#define SYMBOL_FUNC_FLOAT 8
#define SYMBOL_FUNC_CHAR 9
#define SYMBOL_LIT_REAL 10
#define SYMBOL_LIT_INT 11
#define SYMBOL_FUNC_PAR_INT 12
#define SYMBOL_FUNC_PAR_FLOAT 13

#endif
